=== kindiherdiansyah/Tugas-1/order.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT baksokuat (order)+>
<!ATTLIST baksokuat
    xmlns CDATA #FIXED ''>

<!ELEMENT order (kd_customer,nama_costumer,nama_paket,nama_pesanan,harga,jml,
                 total,waktu_pesan,alamat_kirim,telp)>
<!ATTLIST order
    xmlns CDATA #FIXED ''>

<!ELEMENT kd_customer (#PCDATA)>
<!ATTLIST kd_customer
    xmlns CDATA #FIXED ''>

<!ELEMENT nama_costumer (#PCDATA)>
<!ATTLIST nama_costumer
    xmlns CDATA #FIXED ''>

<!ELEMENT nama_paket (#PCDATA)>
<!ATTLIST nama_paket
    xmlns CDATA #FIXED ''>

<!ELEMENT nama_pesanan (#PCDATA)>
<!ATTLIST nama_pesanan
    xmlns CDATA #FIXED ''>

<!ELEMENT harga (#PCDATA)>
<!ATTLIST harga
    xmlns CDATA #FIXED ''>

<!ELEMENT jml (#PCDATA)>
<!ATTLIST jml
    xmlns CDATA #FIXED ''>

<!ELEMENT total (#PCDATA)>
<!ATTLIST total
    xmlns CDATA #FIXED ''>

<!ELEMENT waktu_pesan (#PCDATA)>
<!ATTLIST waktu_pesan
    xmlns CDATA #FIXED ''>

<!ELEMENT alamat_kirim (#PCDATA)>
<!ATTLIST alamat_kirim
    xmlns CDATA #FIXED ''>

<!ELEMENT telp (#PCDATA)>
<!ATTLIST telp
    xmlns CDATA #FIXED ''>

=== kindiherdiansyah/Tugas-1/jasaorder.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE baksokuat SYSTEM "order.dtd">
<baksokuat>
	<order>
		<kd_customer>001</kd_customer>
		<nama_costumer>Kindi Herdiansyah</nama_costumer>
		<nama_paket>Paket A</nama_paket>
		<nama_pesanan>Bakso Exelent</nama_pesanan>
		<harga>Rp.20.000</harga>
		<jml>2</jml>
		<total>40000</total>
		<waktu_pesan>08.00</waktu_pesan>
		<alamat_kirim>Jln. Sariasih No.2</alamat_kirim>
		<telp>081232132244</telp>
	</order>
	<order>
		<kd_customer>002</kd_customer>
		<nama_costumer>Nida Regita</nama_costumer>
		<nama_paket>Paket B</nama_paket>
		<nama_pesanan>Bakso Johan </nama_pesanan>
		<harga>Rp.18.000</harga>
		<jml>2</jml>
		<total>36000</total>
		<waktu_pesan>09.00</waktu_pesan>
		<alamat_kirim>Jln. Sariasih No.2</alamat_kirim>
		<telp>081232903141</telp>
	</order>
	<order>
		<kd_customer>003</kd_customer>
		<nama_costumer>Raisa</nama_costumer>
		<nama_paket>Paket C</nama_paket>
		<nama_pesanan>Bakso Mantan Terindah</nama_pesanan>
		<harga>Rp.45.000</harga>
		<jml>2</jml>
		<total>90000</total>
		<waktu_pesan>08.00</waktu_pesan>
		<alamat_kirim>Jln. Sariasih No.7</alamat_kirim>
		<telp>081232132522</telp>
	</order>
	<order>
		<kd_customer>004</kd_customer>
		<nama_costumer>Boboho</nama_costumer>
		<nama_paket>Paket D</nama_paket>
		<nama_pesanan>Bakso Together</nama_pesanan>
		<harga>Rp.45.000</harga>
		<jml>2</jml>
		<total>90000</total>
		<waktu_pesan>08.00</waktu_pesan>
		<alamat_kirim>Jln. Sariasih No.7</alamat_kirim>
		<telp>08123216265</telp>
	</order>
	<order>
		<kd_customer>005</kd_customer>
		<nama_costumer>Ariel</nama_costumer>
		<nama_paket>Paket E</nama_paket>
		<nama_pesanan>Bakso Separuh Aku</nama_pesanan>
		<harga>Rp.30.000</harga>
		<jml>2</jml>
		<total>60000</total>
		<waktu_pesan>08.00</waktu_pesan>
		<alamat_kirim>Jln. Sariasih No.7</alamat_kirim>
		<telp>081232132423</telp>
	</order>
</baksokuat>
